---
- name: Hello AIOps
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i == 3
      action:
        debug:
          msg: "AI Insight: We reached event number 3!"