---
- name: Listen for Windows Self-Reported Alerts
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5001
  rules:
    - name: Restart Spooler
      condition: event.payload.status == "down" and event.payload.service == "Spooler"
      action:
        run_job_template:
          name: "Restore Windows Service"
          organization: "Default"
          job_args:
            extra_vars:
              service_name: "{{ event.payload.service }}"
